version: '3.9'

services:
  app:
    container_name: app
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    networks:
      - rebase-labs
    environment:
      REDIS_URL: redis://redis:6379/0
    command: bash -c "bundle && ruby server.rb"

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data    
    networks:
      - rebase-labs
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres

  testpostgres:
    container_name: testpostgres
    image: postgres 
    networks:
      - rebase-labs
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres

  redis:
    container_name: redis
    image: redis
    networks:
      - rebase-labs
  
  sidekiq:
    container_name: sidekiq
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    command: bash -c 'sidekiq -r ./app/jobs/my_job.rb'
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - rebase-labs


volumes:
  rubygems:
  pgdata:
  gemconfig:

networks:
  rebase-labs: {}

