#!/bin/bash

docker run -it \
  --rm \
  --name rebase-labs \
  -w /app \
  -v $(pwd):/app \
  -v rubygems_rebase_labs:/usr/local/bundle \
  -v rubygems_rebase_labs:/usr/local/gem/cache \
  -p 3000:3000 \
  --network rebase-labs \
  ruby \
  bash -c "bundler install && bundle && bundle exec rspec --init && ruby server.rb" \

