#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  -w /app \
  -e POSTGRES_HOST_AUTH_METHOD=trust \
  -v $(pwd):/app \
  -v rubygems_rebase_labs:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "gem install rack rspec capybara rack-test sinatra pg puma && ruby server.rb" \

